In [42]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from Pipeline.Model.EvaluationELM import EvaluationELM
from Pipeline.Model.EvaluationMatrix import EvaluationMatrix
from Pipeline.Model.ExtremeLearningMachine import ExtremeLearningMachine

In [43]:
def extract_optimal_vector(dataframe: pd.DataFrame,
                           metric_col: str = 'Clinical_F2_LCB') -> pd.Series:
    return dataframe.dropna(subset=[metric_col]).sort_values(by=metric_col, ascending=False).iloc[0]

In [44]:
filePath = '../../Dataset/UCI_Gallstone_Dataset.csv'
df = pd.read_csv(filePath)

targetCol = ['Gallstone Status']
X = df.drop(targetCol, axis=1)
y = df[targetCol]
features_size = X.shape[1]

In [45]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [46]:
hidden_size_explore = range(40, 61)
lambda_value_explore = np.arange(7.00, 9.00, 0.25)

In [47]:
# 1. Instantiate the Evaluator Object ONCE
evaluator = EvaluationELM(
    x=X,
    y=y,
    activation_function=sigmoid,
    elm_initial_state_range=range(41, 50),
    data_split_state_range=range(1, 6),
    test_size=0.2,
    k_fold=5
)

In [48]:
hidden_size_record ,hidden_size_result = evaluator.grid_search_hidden_size(hidden_size_explore)
hidden_size_result

,Hidden_Nodes,Activation,Lambda_Value,avg_Accuracy_Seed_Mean,avg_Accuracy_Seed_Std,avg_Accuracy_Seed_Min,avg_Accuracy_Seed_Max,avg_Precision_Seed_Mean,avg_Precision_Seed_Std,avg_Precision_Seed_Min,...,avg_F2-Score_Seed_Max,avg_Balanced Accuracy_Seed_Mean,avg_Balanced Accuracy_Seed_Std,avg_Balanced Accuracy_Seed_Min,avg_Balanced Accuracy_Seed_Max,avg_MCC_Seed_Mean,avg_MCC_Seed_Std,avg_MCC_Seed_Min,avg_MCC_Seed_Max,Clinical_F2_LCB
0,40,sigmoid,0.0,0.7075,0.0615,0.5294,0.8627,0.7269,0.0785,0.5185,...,0.8730,0.7069,0.0615,0.5300,0.8631,0.4200,0.1236,0.0601,0.7262,0.4252
1,41,sigmoid,0.0,0.6902,0.0583,0.5490,0.8431,0.7061,0.0743,0.5357,...,0.8397,0.6897,0.0582,0.5500,0.8415,0.3850,0.1182,0.1005,0.6938,0.4187
2,42,sigmoid,0.0,0.6973,0.0643,0.4510,0.8824,0.7138,0.0768,0.4400,...,0.9302,0.6967,0.0645,0.4508,0.8838,0.3998,0.1295,-0.0985,0.7749,0.3866
3,43,sigmoid,0.0,0.6856,0.0607,0.5294,0.8235,0.6993,0.0743,0.5172,...,0.9091,0.6851,0.0607,0.5277,0.8262,0.3760,0.1230,0.0563,0.6745,0.3984
4,44,sigmoid,0.0,0.6983,0.0615,0.4314,0.8431,0.7163,0.0761,0.4167,...,0.8661,0.6979,0.0617,0.4308,0.8438,0.4020,0.1246,-0.1387,0.6888,0.4046
5,45,sigmoid,0.0,0.7055,0.0601,0.5294,0.8627,0.7210,0.0712,0.5357,...,0.8712,0.7051,0.0603,0.5300,0.8623,0.4157,0.1215,0.0601,0.7257,0.4150
6,46,sigmoid,0.0,0.6794,0.0628,0.4706,0.8235,0.6927,0.0748,0.4444,...,0.9091,0.6789,0.0631,0.4677,0.8262,0.3633,0.1276,-0.0676,0.6745,0.3797
7,47,sigmoid,0.0,0.6864,0.0637,0.4902,0.8431,0.7031,0.0774,0.4737,...,0.8915,0.6858,0.0637,0.4877,0.8446,0.3771,0.1283,-0.0255,0.6957,0.3899
8,48,sigmoid,0.0,0.6892,0.0621,0.5098,0.8824,0.7072,0.0730,0.5000,...,0.8846,0.6886,0.0624,0.5115,0.8815,0.3834,0.1254,0.0234,0.7666,0.3699
9,49,sigmoid,0.0,0.6864,0.0613,0.5098,0.8627,0.7028,0.0727,0.5200,...,0.8462,0.6858,0.0613,0.5100,0.8638,0.3772,0.1234,0.0200,0.7311,0.3981
10,50,sigmoid,0.0,0.6945,0.0591,0.5098,0.8431,0.7064,0.0709,0.5000,...,0.8594,0.6940,0.0592,0.5077,0.8438,0.3926,0.1188,0.0158,0.6888,0.4265
11,51,sigmoid,0.0,0.6977,0.0664,0.4902,0.8627,0.7104,0.0791,0.4800,...,0.8759,0.6974,0.0665,0.4900,0.8615,0.4002,0.1338,-0.0200,0.7532,0.4080
12,52,sigmoid,0.0,0.6858,0.0670,0.5098,0.8431,0.7048,0.0795,0.5000,...,0.8661,0.6851,0.0673,0.5077,0.8438,0.3757,0.1354,0.0158,0.6888,0.3593
13,53,sigmoid,0.0,0.6875,0.0648,0.5098,0.8235,0.7036,0.0796,0.5000,...,0.9091,0.6869,0.0652,0.5092,0.8262,0.3800,0.1317,0.0185,0.6745,0.3761
14,54,sigmoid,0.0,0.6891,0.0621,0.5294,0.8627,0.7066,0.0740,0.5357,...,0.8779,0.6885,0.0624,0.5285,0.8631,0.3825,0.1254,0.0572,0.7262,0.3915
15,55,sigmoid,0.0,0.6842,0.0629,0.5098,0.8235,0.6968,0.0793,0.5000,...,0.8527,0.6838,0.0627,0.5092,0.8231,0.3727,0.1271,0.0185,0.6472,0.4170
16,56,sigmoid,0.0,0.7129,0.0629,0.5294,0.8627,0.7274,0.0734,0.5200,...,0.8759,0.7124,0.0632,0.5292,0.8638,0.4305,0.1267,0.0585,0.7311,0.4127
17,57,sigmoid,0.0,0.6960,0.0641,0.5294,0.8431,0.7132,0.0783,0.5185,...,0.9259,0.6955,0.0642,0.5300,0.8431,0.3974,0.1301,0.0601,0.6862,0.3894
18,58,sigmoid,0.0,0.6979,0.0663,0.5294,0.8627,0.7160,0.0829,0.5200,...,0.8730,0.6973,0.0665,0.5277,0.8631,0.4004,0.1350,0.0563,0.7262,0.4086
19,59,sigmoid,0.0,0.6978,0.0584,0.5098,0.8431,0.7152,0.0742,0.5000,...,0.8462,0.6973,0.0586,0.5069,0.8415,0.4010,0.1184,0.0145,0.6938,0.3973
20,60,sigmoid,0.0,0.6974,0.0635,0.5098,0.8431,0.7136,0.0776,0.5000,...,0.8594,0.6969,0.0636,0.5092,0.8423,0.3995,0.1280,0.0185,0.6878,0.4040

In [49]:
best_hidden_size = extract_optimal_vector(hidden_size_result)
best_hidden_size_value = best_hidden_size['Hidden_Nodes']
best_hidden_size

Hidden_Nodes                            50
Activation                         sigmoid
Lambda_Value                           0.0
avg_Accuracy_Seed_Mean              0.6945
avg_Accuracy_Seed_Std               0.0591
avg_Accuracy_Seed_Min               0.5098
avg_Accuracy_Seed_Max               0.8431
avg_Precision_Seed_Mean             0.7064
avg_Precision_Seed_Std              0.0709
avg_Precision_Seed_Min                 0.5
avg_Precision_Seed_Max              0.9444
avg_Recall_Seed_Mean                0.6625
avg_Recall_Seed_Std                 0.0929
avg_Recall_Seed_Min                    0.4
avg_Recall_Seed_Max                   0.88
avg_NPV_Seed_Mean                   0.6908
avg_NPV_Seed_Std                    0.0613
avg_NPV_Seed_Min                    0.5161
avg_NPV_Seed_Max                    0.8696
avg_Specificity_Seed_Mean           0.7256
avg_Specificity_Seed_Std            0.0904
avg_Specificity_Seed_Min            0.4231
avg_Specificity_Seed_Max            0.9615
avg_F1-Score_Seed_Mean                0.68
avg_F1-Score_Seed_Std               0.0672
avg_F1-Score_Seed_Min               0.4444
avg_F1-Score_Seed_Max                 0.84
avg_F2-Score_Seed_Mean              0.6686
avg_F2-Score_Seed_Std               0.0807
avg_F2-Score_Seed_Min               0.4167
avg_F2-Score_Seed_Max               0.8594
avg_Balanced Accuracy_Seed_Mean      0.694
avg_Balanced Accuracy_Seed_Std      0.0592
avg_Balanced Accuracy_Seed_Min      0.5077
avg_Balanced Accuracy_Seed_Max      0.8438
avg_MCC_Seed_Mean                   0.3926
avg_MCC_Seed_Std                    0.1188
avg_MCC_Seed_Min                    0.0158
avg_MCC_Seed_Max                    0.6888
Clinical_F2_LCB                     0.4265
Name: 10, dtype: object

In [50]:
lambda_record, lambda_result = evaluator.grid_search_lambda(
    hidden_size=best_hidden_size_value,
    lambda_range=lambda_value_explore
)
lambda_result

,Hidden_Nodes,Activation,Lambda_Value,avg_Accuracy_Seed_Mean,avg_Accuracy_Seed_Std,avg_Accuracy_Seed_Min,avg_Accuracy_Seed_Max,avg_Precision_Seed_Mean,avg_Precision_Seed_Std,avg_Precision_Seed_Min,...,avg_F2-Score_Seed_Max,avg_Balanced Accuracy_Seed_Mean,avg_Balanced Accuracy_Seed_Std,avg_Balanced Accuracy_Seed_Min,avg_Balanced Accuracy_Seed_Max,avg_MCC_Seed_Mean,avg_MCC_Seed_Std,avg_MCC_Seed_Min,avg_MCC_Seed_Max,Clinical_F2_LCB
0,50,sigmoid,7.00,0.7188,0.0617,0.549,0.8824,0.7390,0.0761,0.5357,...,0.8846,0.7182,0.0618,0.5477,0.8823,0.4430,0.1240,0.0963,0.7646,0.4257
1,50,sigmoid,7.25,0.7191,0.0620,0.549,0.8824,0.7396,0.0763,0.5357,...,0.8846,0.7186,0.0620,0.5477,0.8823,0.4437,0.1244,0.0963,0.7646,0.4249
2,50,sigmoid,7.50,0.7193,0.0619,0.549,0.8824,0.7402,0.0762,0.5357,...,0.8846,0.7188,0.0620,0.5500,0.8823,0.4441,0.1243,0.1005,0.7646,0.4235
3,50,sigmoid,7.75,0.7192,0.0617,0.549,0.8824,0.7401,0.0760,0.5357,...,0.8846,0.7187,0.0617,0.5500,0.8823,0.4439,0.1238,0.1005,0.7646,0.4250
4,50,sigmoid,8.00,0.7197,0.0611,0.549,0.8824,0.7407,0.0758,0.5357,...,0.8846,0.7191,0.0612,0.5500,0.8823,0.4448,0.1228,0.1005,0.7646,0.4275
5,50,sigmoid,8.25,0.7199,0.0614,0.549,0.8824,0.7410,0.0759,0.5357,...,0.8846,0.7194,0.0615,0.5500,0.8823,0.4454,0.1233,0.1005,0.7646,0.4254
6,50,sigmoid,8.50,0.7201,0.0613,0.549,0.8824,0.7412,0.0759,0.5357,...,0.8846,0.7195,0.0614,0.5500,0.8823,0.4458,0.1232,0.1005,0.7646,0.4251
7,50,sigmoid,8.75,0.7197,0.0613,0.549,0.8824,0.7411,0.0760,0.5357,...,0.8846,0.7191,0.0614,0.5500,0.8823,0.4450,0.1232,0.1005,0.7646,0.4233

In [51]:
best_lambda_value = extract_optimal_vector(lambda_result)
best_lambda_value

Hidden_Nodes                            50
Activation                         sigmoid
Lambda_Value                           8.0
avg_Accuracy_Seed_Mean              0.7197
avg_Accuracy_Seed_Std               0.0611
avg_Accuracy_Seed_Min                0.549
avg_Accuracy_Seed_Max               0.8824
avg_Precision_Seed_Mean             0.7407
avg_Precision_Seed_Std              0.0758
avg_Precision_Seed_Min              0.5357
avg_Precision_Seed_Max              0.9333
avg_Recall_Seed_Mean                0.6763
avg_Recall_Seed_Std                 0.0998
avg_Recall_Seed_Min                   0.48
avg_Recall_Seed_Max                 0.8846
avg_NPV_Seed_Mean                    0.711
avg_NPV_Seed_Std                    0.0662
avg_NPV_Seed_Min                    0.5652
avg_NPV_Seed_Max                      0.88
avg_Specificity_Seed_Mean           0.7619
avg_Specificity_Seed_Std            0.0926
avg_Specificity_Seed_Min            0.4615
avg_Specificity_Seed_Max            0.9615
avg_F1-Score_Seed_Mean              0.7023
avg_F1-Score_Seed_Std               0.0699
avg_F1-Score_Seed_Min               0.5217
avg_F1-Score_Seed_Max               0.8846
avg_F2-Score_Seed_Mean              0.6855
avg_F2-Score_Seed_Std                0.086
avg_F2-Score_Seed_Min               0.4959
avg_F2-Score_Seed_Max               0.8846
avg_Balanced Accuracy_Seed_Mean     0.7191
avg_Balanced Accuracy_Seed_Std      0.0612
avg_Balanced Accuracy_Seed_Min        0.55
avg_Balanced Accuracy_Seed_Max      0.8823
avg_MCC_Seed_Mean                   0.4448
avg_MCC_Seed_Std                    0.1228
avg_MCC_Seed_Min                    0.1005
avg_MCC_Seed_Max                    0.7646
Clinical_F2_LCB                     0.4275
Name: 4, dtype: object

In [52]:
combination_record , combination_result = evaluator.grid_search_hidden_size_and_lambda(
    hidden_size_range=hidden_size_explore,
    lambda_range=lambda_value_explore
)
best_combination_result = extract_optimal_vector(combination_result)
best_combination_result

Hidden_Nodes                            60
Activation                         sigmoid
Lambda_Value                          8.75
avg_Accuracy_Seed_Mean              0.7218
avg_Accuracy_Seed_Std               0.0574
avg_Accuracy_Seed_Min                0.549
avg_Accuracy_Seed_Max               0.8627
avg_Precision_Seed_Mean             0.7503
avg_Precision_Seed_Std              0.0811
avg_Precision_Seed_Min              0.5455
avg_Precision_Seed_Max                 1.0
avg_Recall_Seed_Mean                0.6691
avg_Recall_Seed_Std                 0.0916
avg_Recall_Seed_Min                   0.36
avg_Recall_Seed_Max                   0.88
avg_NPV_Seed_Mean                   0.7085
avg_NPV_Seed_Std                     0.059
avg_NPV_Seed_Min                    0.5517
avg_NPV_Seed_Max                    0.8636
avg_Specificity_Seed_Mean           0.7732
avg_Specificity_Seed_Std            0.0961
avg_Specificity_Seed_Min            0.5385
avg_Specificity_Seed_Max               1.0
avg_F1-Score_Seed_Mean              0.7023
avg_F1-Score_Seed_Std               0.0645
avg_F1-Score_Seed_Min               0.5106
avg_F1-Score_Seed_Max               0.8511
avg_F2-Score_Seed_Mean               0.681
avg_F2-Score_Seed_Std               0.0785
avg_F2-Score_Seed_Min               0.4128
avg_F2-Score_Seed_Max               0.8527
avg_Balanced Accuracy_Seed_Mean     0.7212
avg_Balanced Accuracy_Seed_Std      0.0574
avg_Balanced Accuracy_Seed_Min      0.5477
avg_Balanced Accuracy_Seed_Max      0.8615
avg_MCC_Seed_Mean                   0.4503
avg_MCC_Seed_Std                    0.1166
avg_MCC_Seed_Min                    0.0963
avg_MCC_Seed_Max                    0.7298
Clinical_F2_LCB                     0.4455
Name: 167, dtype: object

In [60]:
combination_result

,Hidden_Nodes,Activation,Lambda_Value,avg_Accuracy_Seed_Mean,avg_Accuracy_Seed_Std,avg_Accuracy_Seed_Min,avg_Accuracy_Seed_Max,avg_Precision_Seed_Mean,avg_Precision_Seed_Std,avg_Precision_Seed_Min,...,avg_F2-Score_Seed_Max,avg_Balanced Accuracy_Seed_Mean,avg_Balanced Accuracy_Seed_Std,avg_Balanced Accuracy_Seed_Min,avg_Balanced Accuracy_Seed_Max,avg_MCC_Seed_Mean,avg_MCC_Seed_Std,avg_MCC_Seed_Min,avg_MCC_Seed_Max,Clinical_F2_LCB
0,40,sigmoid,7.00,0.7195,0.0636,0.5294,0.8627,0.7455,0.0828,0.5217,...,0.8730,0.7188,0.0637,0.5285,0.8631,0.4452,0.1278,0.0572,0.7298,0.4166
1,40,sigmoid,7.25,0.7189,0.0636,0.5294,0.8627,0.7452,0.0825,0.5217,...,0.8730,0.7182,0.0636,0.5285,0.8631,0.4441,0.1277,0.0572,0.7298,0.4127
2,40,sigmoid,7.50,0.7183,0.0635,0.5294,0.8627,0.7449,0.0826,0.5217,...,0.8730,0.7176,0.0636,0.5285,0.8631,0.4431,0.1277,0.0572,0.7298,0.4117
3,40,sigmoid,7.75,0.7179,0.0633,0.5294,0.8627,0.7443,0.0820,0.5217,...,0.8730,0.7172,0.0634,0.5285,0.8631,0.4421,0.1274,0.0572,0.7298,0.4116
4,40,sigmoid,8.00,0.7173,0.0632,0.5294,0.8627,0.7438,0.0818,0.5217,...,0.8730,0.7166,0.0633,0.5285,0.8631,0.4409,0.1272,0.0572,0.7298,0.4114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,60,sigmoid,7.75,0.7219,0.0578,0.5686,0.8627,0.7495,0.0816,0.5556,...,0.8400,0.7213,0.0579,0.5669,0.8615,0.4504,0.1175,0.1360,0.7298,0.4450
164,60,sigmoid,8.00,0.7217,0.0581,0.5686,0.8627,0.7497,0.0820,0.5556,...,0.8527,0.7210,0.0581,0.5669,0.8615,0.4500,0.1180,0.1360,0.7298,0.4425
165,60,sigmoid,8.25,0.7216,0.0580,0.5490,0.8627,0.7498,0.0819,0.5455,...,0.8527,0.7209,0.0580,0.5477,0.8615,0.4498,0.1179,0.0963,0.7298,0.4425
166,60,sigmoid,8.50,0.7212,0.0577,0.5490,0.8627,0.7496,0.0810,0.5455,...,0.8527,0.7205,0.0577,0.5477,0.8615,0.4491,0.1171,0.0963,0.7298,0.4421
167,60,sigmoid,8.75,0.7218,0.0574,0.5490,0.8627,0.7503,0.0811,0.5455,...,0.8527,0.7212,0.0574,0.5477,0.8615,0.4503,0.1166,0.0963,0.7298,0.4455

In [53]:
hidden_size_smaller = range(features_size // 2, int(best_hidden_size_value) - 5)
lambda_value_wider = np.linspace(1, 10, 5)

optimization_record,optimization_result = evaluator.grid_search_hidden_size_and_lambda(
    hidden_size_range=hidden_size_smaller,
    lambda_range=lambda_value_wider
)
optimization_result

,Hidden_Nodes,Activation,Lambda_Value,avg_Accuracy_Seed_Mean,avg_Accuracy_Seed_Std,avg_Accuracy_Seed_Min,avg_Accuracy_Seed_Max,avg_Precision_Seed_Mean,avg_Precision_Seed_Std,avg_Precision_Seed_Min,...,avg_F2-Score_Seed_Max,avg_Balanced Accuracy_Seed_Mean,avg_Balanced Accuracy_Seed_Std,avg_Balanced Accuracy_Seed_Min,avg_Balanced Accuracy_Seed_Max,avg_MCC_Seed_Mean,avg_MCC_Seed_Std,avg_MCC_Seed_Min,avg_MCC_Seed_Max,Clinical_F2_LCB
0,19,sigmoid,1.00,0.6575,0.0604,0.4902,0.8039,0.6718,0.0750,0.5000,...,0.8519,0.6569,0.0605,0.4908,0.8023,0.3198,0.1227,-0.0185,0.6141,0.3423
1,19,sigmoid,3.25,0.6595,0.0600,0.4118,0.8039,0.6749,0.0746,0.4000,...,0.8582,0.6589,0.0601,0.4138,0.8046,0.3238,0.1218,-0.1764,0.6102,0.3464
2,19,sigmoid,5.50,0.6590,0.0627,0.4118,0.7843,0.6760,0.0776,0.4000,...,0.8582,0.6584,0.0628,0.4138,0.7854,0.3229,0.1272,-0.1764,0.5734,0.3297
3,19,sigmoid,7.75,0.6577,0.0644,0.4118,0.8039,0.6762,0.0806,0.4000,...,0.8519,0.6570,0.0645,0.4138,0.8023,0.3207,0.1310,-0.1764,0.6141,0.3171
4,19,sigmoid,10.00,0.6541,0.0645,0.4314,0.8039,0.6742,0.0809,0.4211,...,0.8271,0.6534,0.0646,0.4338,0.8023,0.3136,0.1310,-0.1368,0.6141,0.3019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,44,sigmoid,1.00,0.7045,0.0614,0.4510,0.8627,0.7240,0.0766,0.4348,...,0.8955,0.7040,0.0615,0.4500,0.8646,0.4149,0.1244,-0.1005,0.7407,0.4054
126,44,sigmoid,3.25,0.7132,0.0577,0.4902,0.8627,0.7352,0.0741,0.4783,...,0.8955,0.7127,0.0578,0.4892,0.8646,0.4327,0.1169,-0.0216,0.7407,0.4233
127,44,sigmoid,5.50,0.7149,0.0572,0.5098,0.8627,0.7368,0.0741,0.5000,...,0.8889,0.7144,0.0572,0.5085,0.8646,0.4361,0.1161,0.0171,0.7407,0.4263
128,44,sigmoid,7.75,0.7182,0.0571,0.5098,0.8627,0.7416,0.0753,0.5000,...,0.8889,0.7176,0.0571,0.5077,0.8638,0.4428,0.1161,0.0158,0.7311,0.4304
129,44,sigmoid,10.00,0.7194,0.0564,0.5098,0.8627,0.7443,0.0748,0.5000,...,0.8889,0.7188,0.0565,0.5077,0.8638,0.4454,0.1148,0.0158,0.7311,0.4317

In [54]:
best_optimization_result = extract_optimal_vector(optimization_result)
best_optimization_result

Hidden_Nodes                            44
Activation                         sigmoid
Lambda_Value                          10.0
avg_Accuracy_Seed_Mean              0.7194
avg_Accuracy_Seed_Std               0.0564
avg_Accuracy_Seed_Min               0.5098
avg_Accuracy_Seed_Max               0.8627
avg_Precision_Seed_Mean             0.7443
avg_Precision_Seed_Std              0.0748
avg_Precision_Seed_Min                 0.5
avg_Precision_Seed_Max              0.9375
avg_Recall_Seed_Mean                0.6695
avg_Recall_Seed_Std                 0.0983
avg_Recall_Seed_Min                    0.4
avg_Recall_Seed_Max                   0.96
avg_NPV_Seed_Mean                   0.7091
avg_NPV_Seed_Std                    0.0656
avg_NPV_Seed_Min                    0.5161
avg_NPV_Seed_Max                    0.9375
avg_Specificity_Seed_Mean           0.7681
avg_Specificity_Seed_Std            0.0909
avg_Specificity_Seed_Min            0.4615
avg_Specificity_Seed_Max            0.9615
avg_F1-Score_Seed_Mean              0.7001
avg_F1-Score_Seed_Std               0.0656
avg_F1-Score_Seed_Min               0.4444
avg_F1-Score_Seed_Max               0.8571
avg_F2-Score_Seed_Mean              0.6804
avg_F2-Score_Seed_Std               0.0829
avg_F2-Score_Seed_Min               0.4167
avg_F2-Score_Seed_Max               0.8889
avg_Balanced Accuracy_Seed_Mean     0.7188
avg_Balanced Accuracy_Seed_Std      0.0565
avg_Balanced Accuracy_Seed_Min      0.5077
avg_Balanced Accuracy_Seed_Max      0.8638
avg_MCC_Seed_Mean                   0.4454
avg_MCC_Seed_Std                    0.1148
avg_MCC_Seed_Min                    0.0158
avg_MCC_Seed_Max                    0.7311
Clinical_F2_LCB                     0.4317
Name: 129, dtype: object

In [55]:
model_configs = [
    {
        "Hidden_Nodes": best_hidden_size['Hidden_Nodes'],
        "Activation": sigmoid,
        "Lambda_Value": best_hidden_size['Lambda_Value']
    },
    {
        "Hidden_Nodes": best_lambda_value['Hidden_Nodes'],
        "Activation": sigmoid,
        "Lambda_Value": best_lambda_value['Lambda_Value']
    },
    {
        "Hidden_Nodes": best_combination_result['Hidden_Nodes'],
        "Activation": sigmoid,
        "Lambda_Value": best_combination_result['Lambda_Value']
    },
    {
        "Hidden_Nodes": best_optimization_result['Hidden_Nodes'],
        "Activation": sigmoid,
        "Lambda_Value": best_optimization_result['Lambda_Value']
    }
]

In [56]:
x_train, x_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

x_test = x_test.reset_index(drop=True)
y_test = y_test.reset_index(drop=True)
x_train = x_train.reset_index(drop=True)
y_train = y_train.reset_index(drop=True)


main_scaler = StandardScaler()
x_train_scaled = pd.DataFrame(main_scaler.fit_transform(x_train), columns=X.columns)
x_test_scaled  = pd.DataFrame(main_scaler.transform(x_test), columns=X.columns)

In [57]:
testing_results = []
for config in model_configs:
    print(f"=== Executing: Nodes : {config['Hidden_Nodes']} , lambda value : {config['Lambda_Value']} , activation function :{config['Activation']}")

    elm = ExtremeLearningMachine(
        features_size=features_size,
        hidden_size=config["Hidden_Nodes"],
        activation_function=config["Activation"],
        regularization_lambda=config["Lambda_Value"]
    )
    elm.initialize_random_weights(random_seed=42)


    elm.fit(x_train_scaled.values, y_train.values)
    y_pred = elm.predict(x_test_scaled.values)

    evaluation = EvaluationMatrix(y_test, y_pred)
    print(evaluation.get_report())

    metrics = evaluation.get_all_metrics()
    test_result = {
        "Hidden_Nodes" : config['Hidden_Nodes'],
        "Lambda_Value" : config['Lambda_Value'],
        "Activation"   : config['Activation']
    }
    test_result.update(metrics)
    testing_results.append(test_result)
    print("\n")

=== Executing: Nodes : 50 , lambda value : 0.0 , activation function :<function sigmoid at 0x000002BC2FFA4400>
{'Counts': {'TP': np.int64(21), 'TN': np.int64(25), 'FP': np.int64(7), 'FN': np.int64(11)}, 'Metrics': {'Accuracy': np.float64(0.7188), 'Precision': np.float64(0.75), 'Recall': np.float64(0.6562), 'NPV': np.float64(0.6944), 'Specificity': np.float64(0.7812), 'F1-Score': np.float64(0.7), 'F2-Score': np.float64(0.6731), 'Balanced Accuracy': np.float64(0.7188), 'MCC': np.float64(0.441)}}


=== Executing: Nodes : 50 , lambda value : 8.0 , activation function :<function sigmoid at 0x000002BC2FFA4400>
{'Counts': {'TP': np.int64(21), 'TN': np.int64(26), 'FP': np.int64(6), 'FN': np.int64(11)}, 'Metrics': {'Accuracy': np.float64(0.7344), 'Precision': np.float64(0.7778), 'Recall': np.float64(0.6562), 'NPV': np.float64(0.7027), 'Specificity': np.float64(0.8125), 'F1-Score': np.float64(0.7119), 'F2-Score': np.float64(0.6774), 'Balanced Accuracy': np.float64(0.7344), 'MCC': np.float64(0.4746)}}


=== Executing: Nodes : 60 , lambda value : 8.75 , activation function :<function sigmoid at 0x000002BC2FFA4400>
{'Counts': {'TP': np.int64(26), 'TN': np.int64(27), 'FP': np.int64(5), 'FN': np.int64(6)}, 'Metrics': {'Accuracy': np.float64(0.8281), 'Precision': np.float64(0.8387), 'Recall': np.float64(0.8125), 'NPV': np.float64(0.8182), 'Specificity': np.float64(0.8438), 'F1-Score': np.float64(0.8254), 'F2-Score': np.float64(0.8176), 'Balanced Accuracy': np.float64(0.8281), 'MCC': np.float64(0.6566)}}


=== Executing: Nodes : 44 , lambda value : 10.0 , activation function :<function sigmoid at 0x000002BC2FFA4400>
{'Counts': {'TP': np.int64(22), 'TN': np.int64(26), 'FP': np.int64(6), 'FN': np.int64(10)}, 'Metrics': {'Accuracy': np.float64(0.75), 'Precision': np.float64(0.7857), 'Recall': np.float64(0.6875), 'NPV': np.float64(0.7222), 'Specificity': np.float64(0.8125), 'F1-Score': np.float64(0.7333), 'F2-Score': np.float64(0.7051), 'Balanced Accuracy': np.float64(0.75), 'MCC': np.float64(0.504)}}

In [58]:
final_model_result = pd.DataFrame(testing_results)
final_model_result

,Hidden_Nodes,Lambda_Value,Activation,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Balanced Accuracy,MCC
0,50,0.00,<function sigmoid at 0x000002BC2FFA4400>,0.718750,0.750000,0.65625,0.694444,0.78125,0.700000,0.673077,0.718750,0.440959
1,50,8.00,<function sigmoid at 0x000002BC2FFA4400>,0.734375,0.777778,0.65625,0.702703,0.81250,0.711864,0.677419,0.734375,0.474579
2,60,8.75,<function sigmoid at 0x000002BC2FFA4400>,0.828125,0.838710,0.81250,0.818182,0.84375,0.825397,0.817610,0.828125,0.656571
3,44,10.00,<function sigmoid at 0x000002BC2FFA4400>,0.750000,0.785714,0.68750,0.722222,0.81250,0.733333,0.705128,0.750000,0.503953