In [1]:
from Pipeline.Global.GlobalSetting import GlobalSetting
from Pipeline.Global.Plotting import Plotting
from Pipeline.Methodology import ABC_Testing

In [2]:
all_trace_record, result_summary = ABC_Testing.lcb_trace_evaluation("../Limit History")

In [3]:
summary_for_evaluation = result_summary.drop(columns=['Employed_Algo3','Onlooker_Algo3','expr_name','metric_name','scout_avg','scout_std','train_MCC_LCB_Mean','train_MCC_LCB_std','train_MCC_LCB_sem','train_MCC_trace_floor'])
summary_for_evaluation['SN/TL'] = summary_for_evaluation['Trial_Limit']/summary_for_evaluation['Solution_Size']

In [4]:
summary_for_evaluation

,Solution_Size,Trial_Limit,Max_Iteration,val_MCC_LCB_Mean,val_MCC_LCB_std,val_MCC_LCB_sem,val_MCC_trace_floor,SN/TL
0,100,100,120,0.549574,0.047330,0.008641,0.527280,1.0
1,100,100,250,0.551243,0.044502,0.008125,0.530280,1.0
2,100,150,120,0.563554,0.033749,0.006162,0.547657,1.5
3,100,150,250,0.552157,0.037243,0.006800,0.534614,1.5
4,100,200,120,0.552708,0.043794,0.007996,0.532079,2.0
5,100,200,250,0.547535,0.045717,0.008347,0.526001,2.0
6,100,50,120,0.551810,0.031135,0.005684,0.537144,0.5
7,100,50,250,0.553254,0.042669,0.007790,0.533156,0.5
8,10,10,1000,0.553543,0.049435,0.009026,0.530257,1.0
9,10,10,120,0.547043,0.047136,0.008606,0.524839,1.0
10,10,15,1000,0.554509,0.040669,0.007425,0.535352,1.5
11,10,15,120,0.557809,0.048589,0.008871,0.534921,1.5
12,10,20,1000,0.550327,0.042476,0.007755,0.530319,2.0
13,10,20,120,0.541767,0.060716,0.011085,0.513168,2.0
14,10,5,1000,0.557916,0.051213,0.009350,0.533793,0.5
15,10,5,120,0.560219,0.047051,0.008590,0.538056,0.5
16,20,10,250,0.547813,0.050494,0.009219,0.524029,0.5
17,20,20,250,0.553546,0.047079,0.008595,0.531370,1.0
18,20,30,250,0.566626,0.033541,0.006124,0.550827,1.5
19,20,40,250,0.548440,0.059412,0.010847,0.520455,2.0
20,50,100,100,0.540277,0.039982,0.007300,0.521444,2.0
21,50,100,150,0.547401,0.047616,0.008694,0.524971,2.0
22,50,25,100,0.533838,0.053701,0.009804,0.508543,0.5
23,50,25,150,0.553579,0.041906,0.007651,0.533839,0.5
24,50,50,100,0.565322,0.046676,0.008522,0.543336,1.0
25,50,50,150,0.542144,0.040573,0.007407,0.523033,1.0
26,50,75,100,0.554932,0.056728,0.010357,0.528211,1.5
27,50,75,150,0.560374,0.041210,0.007524,0.540963,1.5
28,80,120,120,0.557253,0.037348,0.006819,0.539661,1.5
29,80,160,120,0.548806,0.044857,0.008190,0.527676,2.0
30,80,40,120,0.550089,0.037540,0.006854,0.532406,0.5
31,80,80,120,0.555390,0.043620,0.007964,0.534843,1.0

In [5]:
summary_floor = summary_for_evaluation[['SN/TL','val_MCC_trace_floor']]
summary_floor

    SN/TL  val_MCC_trace_floor
0     1.0             0.527280
1     1.0             0.530280
2     1.5             0.547657
3     1.5             0.534614
4     2.0             0.532079
5     2.0             0.526001
6     0.5             0.537144
7     0.5             0.533156
8     1.0             0.530257
9     1.0             0.524839
10    1.5             0.535352
11    1.5             0.534921
12    2.0             0.530319
13    2.0             0.513168
14    0.5             0.533793
15    0.5             0.538056
16    0.5             0.524029
17    1.0             0.531370
18    1.5             0.550827
19    2.0             0.520455
20    2.0             0.521444
21    2.0             0.524971
22    0.5             0.508543
23    0.5             0.533839
24    1.0             0.543336
25    1.0             0.523033
26    1.5             0.528211
27    1.5             0.540963
28    1.5             0.539661
29    2.0             0.527676
30    0.5             0.532406
31    1.0             0.534843

In [6]:
df = summary_floor.groupby(['SN/TL']).agg(['mean', 'std', 'sem'])
df.columns = ['_'.join(col).strip() for col in df.columns.values]
df = df.reset_index()

df['Triple LCB'] = df['val_MCC_trace_floor_mean'] - GlobalSetting.seed_punish_coe * df['val_MCC_trace_floor_sem']
df

,SN/TL,val_MCC_trace_floor_mean,val_MCC_trace_floor_std,val_MCC_trace_floor_sem,Triple LCB
0,0.5,0.530121,0.009686,0.003425,0.521285
1,1.0,0.530655,0.006352,0.002246,0.524860
2,1.5,0.539026,0.007413,0.002621,0.532264
3,2.0,0.524514,0.006071,0.002146,0.518976