In [1]:
import pandas as pd

In [2]:
def extract_best_seed(df):
    numeric_cols = df.select_dtypes(include=['number']).columns
    stats = df.groupby('Seed')[numeric_cols].agg(['mean', 'std'])

    stats.columns = [f"{col}_{stat}" for col, stat in stats.columns]
    stats['MCC_LCB'] = stats['MCC_mean'] - stats['MCC_std']

    target_columns = [
        'Accuracy_mean', 'Accuracy_std',
        'F1-Score_mean', 'F1-Score_std',
        'MCC_mean', 'MCC_std', 'MCC_LCB'
    ]
    best_result = stats.reset_index()[['Seed'] + target_columns]
    best_result = best_result.sort_values(['MCC_LCB'], ascending=False).iloc[[0]]
    return best_result

In [3]:
abc_relm_cv = pd.read_csv('cleaned_ABC_RELM_CV_Algo_3_2_80SN_120MI_Results.csv')
extract_best_seed(abc_relm_cv)

,Seed,Accuracy_mean,Accuracy_std,F1-Score_mean,F1-Score_std,MCC_mean,MCC_std,MCC_LCB
10,22742,0.801835,0.018562,0.784018,0.027915,0.609521,0.034085,0.575436

In [4]:
relm = pd.read_csv('cleaned_Grid_Optimization_Results.csv')
extract_best_seed(relm)

,Seed,Accuracy_mean,Accuracy_std,F1-Score_mean,F1-Score_std,MCC_mean,MCC_std,MCC_LCB
37,77844,0.81126,0.038739,0.794068,0.044401,0.628154,0.075394,0.552759

In [5]:
abc_relm = pd.read_csv('cleaned_ABC_RELM_Algo_3_2_80SN_120MI_Results.csv')
extract_best_seed(abc_relm)

,Seed,Accuracy_mean,Accuracy_std,F1-Score_mean,F1-Score_std,MCC_mean,MCC_std,MCC_LCB
39,78586,0.817659,0.025998,0.7977,0.035076,0.644717,0.048264,0.596453