In [1]:
from Pipeline.Global.Plotting import Plotting
from Pipeline.Methodology import ABC_Testing

In [2]:
all_trace_record, result_summary = ABC_Testing.lcb_trace_evaluation("../Algo History")

In [3]:
summary_for_evaluation = result_summary.drop(columns=['Trial_Limit','expr_name','metric_name','scout_avg','scout_std','train_MCC_LCB_Mean','train_MCC_LCB_std','train_MCC_LCB_sem','train_MCC_trace_floor'])

In [4]:
summary_for_evaluation

,Solution_Size,Max_Iteration,Employed_Algo3,Onlooker_Algo3,val_MCC_LCB_Mean,val_MCC_LCB_std,val_MCC_LCB_sem,val_MCC_trace_floor
0,100,100,False,False,0.553075,0.039233,0.007163,0.534594
1,100,250,False,False,0.563736,0.031232,0.005702,0.549024
2,10,1000,False,False,0.572297,0.042456,0.007751,0.552299
3,10,120,False,False,0.542387,0.037018,0.006759,0.524950
4,20,250,False,False,0.536902,0.039235,0.007163,0.518421
5,50,150,False,False,0.548370,0.048750,0.008900,0.525407
6,80,120,False,False,0.566198,0.049307,0.009002,0.542973
7,100,100,False,True,0.543565,0.044673,0.008156,0.522522
8,100,250,False,True,0.544118,0.034975,0.006386,0.527644
9,10,1000,False,True,0.538520,0.046383,0.008468,0.516671
10,10,120,False,True,0.562876,0.037755,0.006893,0.545092
11,20,250,False,True,0.556832,0.053065,0.009688,0.531836
12,50,150,False,True,0.550885,0.047409,0.008656,0.528553
13,80,120,False,True,0.571143,0.037852,0.006911,0.553313
14,100,100,True,False,0.558615,0.038091,0.006954,0.540673
15,100,250,True,False,0.553254,0.042669,0.007790,0.533156
16,10,1000,True,False,0.557916,0.051213,0.009350,0.533793
17,10,120,True,False,0.560219,0.047051,0.008590,0.538056
18,20,250,True,False,0.547813,0.050494,0.009219,0.524029
19,50,150,True,False,0.553579,0.041906,0.007651,0.533839
20,80,120,True,False,0.550089,0.037540,0.006854,0.532406
21,100,100,True,True,0.568516,0.042187,0.007702,0.548644
22,100,250,True,True,0.558438,0.037886,0.006917,0.540592
23,10,1000,True,True,0.555171,0.038059,0.006949,0.537244
24,10,120,True,True,0.548908,0.040369,0.007370,0.529892
25,20,250,True,True,0.569260,0.049203,0.008983,0.546083
26,50,150,True,True,0.537380,0.039845,0.007275,0.518611
27,80,120,True,True,0.557717,0.036465,0.006658,0.540541

In [5]:
summary_floor = summary_for_evaluation[['Employed_Algo3','Onlooker_Algo3','val_MCC_trace_floor']]
summary_floor

    Employed_Algo3  Onlooker_Algo3  val_MCC_trace_floor
0            False           False             0.534594
1            False           False             0.549024
2            False           False             0.552299
3            False           False             0.524950
4            False           False             0.518421
5            False           False             0.525407
6            False           False             0.542973
7            False            True             0.522522
8            False            True             0.527644
9            False            True             0.516671
10           False            True             0.545092
11           False            True             0.531836
12           False            True             0.528553
13           False            True             0.553313
14            True           False             0.540673
15            True           False             0.533156
16            True           False             0.533793
17            True           False             0.538056
18            True           False             0.524029
19            True           False             0.533839
20            True           False             0.532406
21            True            True             0.548644
22            True            True             0.540592
23            True            True             0.537244
24            True            True             0.529892
25            True            True             0.546083
26            True            True             0.518611
27            True            True             0.540541

In [6]:
df = summary_floor.groupby(['Employed_Algo3', 'Onlooker_Algo3']).agg(['mean', 'std', 'sem'])
df.columns = ['_'.join(col).strip() for col in df.columns.values]
df = df.reset_index()

df['Triple LCB'] = df['val_MCC_trace_floor_mean'] - df['val_MCC_trace_floor_std']
df

,Employed_Algo3,Onlooker_Algo3,val_MCC_trace_floor_mean,val_MCC_trace_floor_std,val_MCC_trace_floor_sem,Triple LCB
0,False,False,0.535381,0.013080,0.004944,0.522301
1,False,True,0.532233,0.012786,0.004833,0.519447
2,True,False,0.533707,0.005214,0.001971,0.528493
3,True,True,0.537373,0.010257,0.003877,0.527115