In [1]:
from Pipeline.Global.GlobalSetting import GlobalSetting
from Pipeline.Methodology import ABC_Testing

In [2]:
all_trace_record, result_summary = ABC_Testing.lcb_trace_evaluation("../Algo History")

In [3]:
summary_for_evaluation = result_summary.drop(columns=['Trial_Limit','expr_name','metric_name','scout_avg','scout_std','train_MCC_LCB_Mean','train_MCC_LCB_std','train_MCC_LCB_sem','train_MCC_trace_floor'])

In [4]:
summary_for_evaluation.sort_values(['Solution_Size','Max_Iteration','Employed_Algo3','Onlooker_Algo3',])

,Solution_Size,Max_Iteration,Employed_Algo3,Onlooker_Algo3,val_MCC_LCB_Mean,val_MCC_LCB_std,val_MCC_LCB_sem,val_MCC_trace_floor
3,10,120,False,False,0.542387,0.037018,0.006759,0.524950
11,10,120,False,True,0.562876,0.037755,0.006893,0.545092
19,10,120,True,False,0.560219,0.047051,0.008590,0.538056
27,10,120,True,True,0.548908,0.040369,0.007370,0.529892
2,10,1000,False,False,0.572297,0.042456,0.007751,0.552299
10,10,1000,False,True,0.538520,0.046383,0.008468,0.516671
18,10,1000,True,False,0.557916,0.051213,0.009350,0.533793
26,10,1000,True,True,0.555171,0.038059,0.006949,0.537244
4,20,250,False,False,0.536902,0.039235,0.007163,0.518421
12,20,250,False,True,0.556832,0.053065,0.009688,0.531836
20,20,250,True,False,0.547813,0.050494,0.009219,0.524029
28,20,250,True,True,0.569260,0.049203,0.008983,0.546083
5,50,150,False,False,0.548370,0.048750,0.008900,0.525407
13,50,150,False,True,0.550885,0.047409,0.008656,0.528553
21,50,150,True,False,0.553579,0.041906,0.007651,0.533839
29,50,150,True,True,0.537380,0.039845,0.007275,0.518611
6,80,120,False,False,0.566198,0.049307,0.009002,0.542973
14,80,120,False,True,0.571143,0.037852,0.006911,0.553313
22,80,120,True,False,0.550089,0.037540,0.006854,0.532406
30,80,120,True,True,0.557717,0.036465,0.006658,0.540541
7,80,250,False,False,0.555777,0.039965,0.007297,0.536952
15,80,250,False,True,0.560370,0.047995,0.008763,0.537763
23,80,250,True,False,0.549949,0.048626,0.008878,0.527044
31,80,250,True,True,0.555059,0.048124,0.008786,0.532391
0,100,120,False,False,0.558257,0.042923,0.007837,0.538039
8,100,120,False,True,0.547319,0.046311,0.008455,0.525505
16,100,120,True,False,0.551810,0.031135,0.005684,0.537144
24,100,120,True,True,0.566868,0.051577,0.009417,0.542574
1,100,250,False,False,0.563736,0.031232,0.005702,0.549024
9,100,250,False,True,0.544118,0.034975,0.006386,0.527644
17,100,250,True,False,0.553254,0.042669,0.007790,0.533156
25,100,250,True,True,0.558438,0.037886,0.006917,0.540592

In [5]:
summary_floor = summary_for_evaluation[['Employed_Algo3','Onlooker_Algo3','val_MCC_trace_floor']]
summary_floor

    Employed_Algo3  Onlooker_Algo3  val_MCC_trace_floor
0            False           False             0.538039
1            False           False             0.549024
2            False           False             0.552299
3            False           False             0.524950
4            False           False             0.518421
5            False           False             0.525407
6            False           False             0.542973
7            False           False             0.536952
8            False            True             0.525505
9            False            True             0.527644
10           False            True             0.516671
11           False            True             0.545092
12           False            True             0.531836
13           False            True             0.528553
14           False            True             0.553313
15           False            True             0.537763
16            True           False             0.537144
17            True           False             0.533156
18            True           False             0.533793
19            True           False             0.538056
20            True           False             0.524029
21            True           False             0.533839
22            True           False             0.532406
23            True           False             0.527044
24            True            True             0.542574
25            True            True             0.540592
26            True            True             0.537244
27            True            True             0.529892
28            True            True             0.546083
29            True            True             0.518611
30            True            True             0.540541
31            True            True             0.532391

In [6]:
df = summary_floor.groupby(['Employed_Algo3', 'Onlooker_Algo3']).agg(['mean', 'std', 'sem'])
df.columns = ['_'.join(col).strip() for col in df.columns.values]
df = df.reset_index()

df['Triple LCB'] = df['val_MCC_trace_floor_mean'] - GlobalSetting.seed_punish_coe * df['val_MCC_trace_floor_std']
df

,Employed_Algo3,Onlooker_Algo3,val_MCC_trace_floor_mean,val_MCC_trace_floor_std,val_MCC_trace_floor_sem,Triple LCB
0,False,False,0.536008,0.012144,0.004293,0.504677
1,False,True,0.533297,0.011671,0.004126,0.503187
2,True,False,0.532433,0.004748,0.001679,0.520182
3,True,True,0.535991,0.008790,0.003108,0.513313