In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('UCI_Gallstone_Dataset.csv')

categorical_vars = [
    'Gallstone Status', 'Gender', 'Comorbidity',
    'Coronary Artery Disease (CAD)', 'Hypothyroidism',
    'Hyperlipidemia', 'Diabetes Mellitus (DM)', 'Hepatic Fat Accumulation (HFA)'
]
continuous_vars = [col for col in df.columns if col not in categorical_vars]
summary_list = []

for col in categorical_vars:
    try:
        temp_col = pd.to_numeric(df[col])
    except (ValueError, TypeError):
        temp_col = df[col]

    counts = temp_col.value_counts(dropna=False).sort_index()
    percentages = temp_col.value_counts(normalize=True, dropna=False).sort_index() * 100

    n_list = [int(c) for c in counts.values]
    pct_list = [f"({p:.1f}%)" for p in percentages.values]

    clean_categories = [int(idx) if pd.notna(idx) and isinstance(idx, (int, float)) else ('Missing' if pd.isna(idx) else idx) for idx in counts.index]

    feature_names = [col] + [''] * (len(counts) - 1)

    temp_df = pd.DataFrame({
        'Characteristic': feature_names,
        'Category': clean_categories,
        'N': n_list,
        '(%)': pct_list
    })
    summary_list.append(temp_df)

In [3]:
cat_table = pd.concat(summary_list, ignore_index=True)
cat_table

                    Characteristic  Category    N      (%)
0                 Gallstone Status         0  161  (50.5%)
1                                          1  158  (49.5%)
2                           Gender         0  162  (50.8%)
3                                          1  157  (49.2%)
4                      Comorbidity         0  217  (68.0%)
5                                          1   99  (31.0%)
6                                          2    1   (0.3%)
7                                          3    2   (0.6%)
8    Coronary Artery Disease (CAD)         0  307  (96.2%)
9                                          1   12   (3.8%)
10                  Hypothyroidism         0  310  (97.2%)
11                                         1    9   (2.8%)
12                  Hyperlipidemia         0  311  (97.5%)
13                                         1    8   (2.5%)
14          Diabetes Mellitus (DM)         0  276  (86.5%)
15                                         1   43  (13.5%)
16  Hepatic Fat Accumulation (HFA)         0  129  (40.4%)
17                                         1   41  (12.9%)
18                                         2  122  (38.2%)
19                                         3   26   (8.2%)
20                                         4    1   (0.3%)

In [4]:
cont_table = df[continuous_vars]
stat_df = cont_table.describe()

In [5]:
one_decimal = ['Age', 'Height','Weight', 'Body Mass Index (BMI)','Total Body Water (TBW)', 'Extracellular Water (ECW)',
               'Intracellular Water (ICW)','Bone Mass (BM)', 'Muscle Mass (MM)','Total Fat Content (TFC)','Visceral Muscle Area (VMA) (Kg)','Visceral Fat Rating (VFR)' ,'Glucose', 'Total Cholesterol (TC)',
       'Low Density Lipoprotein (LDL)', 'High Density Lipoprotein (HDL)',
       'Triglyceride', 'Aspartat Aminotransferaz (AST)','Alanin Aminotransferaz (ALT)', 'Alkaline Phosphatase (ALP)',]
two_decimal = ['Extracellular Fluid/Total Body Water (ECF/TBW)','Total Body Fat Ratio (TBFR) (%)','Lean Mass (LM) (%)','Body Protein Content (Protein) (%)','Obesity (%)','Visceral Fat Area (VFA)','Creatinine', 'Glomerular Filtration Rate (GFR)',
       'C-Reactive Protein (CRP)', 'Hemoglobin (HGB)', 'Vitamin D']

formatted_stat_df = stat_df.copy().astype(object)

for col in stat_df.columns:
    formatted_stat_df.loc['count', col] = int(stat_df.loc['count', col])
    other_rows = stat_df.index != 'count'

    if col in one_decimal:
        formatted_stat_df.loc[other_rows, col] = stat_df.loc[other_rows, col].round(1)
    elif col in two_decimal:
        formatted_stat_df.loc[other_rows, col] = stat_df.loc[other_rows, col].round(2)

In [6]:
formatted_stat_df.transpose()

,count,mean,std,min,25%,50%,75%,max
Age,319,48.1,12.1,20.0,38.5,49.0,56.0,96.0
Height,319,167.2,10.1,145.0,159.5,168.0,175.0,191.0
Weight,319,80.6,15.7,42.9,69.6,78.8,91.2,143.5
Body Mass Index (BMI),319,28.9,5.3,17.4,25.2,28.3,31.8,49.7
Total Body Water (TBW),319,40.6,7.9,13.0,34.2,39.8,47.0,66.2
Extracellular Water (ECW),319,17.1,3.2,9.0,14.8,17.1,19.4,27.8
Intracellular Water (ICW),319,23.6,5.3,13.8,19.3,23.0,27.6,57.1
Extracellular Fluid/Total Body Water (ECF/TBW),319,42.21,3.24,29.23,40.08,42.0,44.0,52.0
Total Body Fat Ratio (TBFR) (%),319,28.27,8.44,6.3,22.02,27.82,34.81,50.92
Lean Mass (LM) (%),319,71.64,8.44,48.99,65.17,72.11,77.85,93.67
Body Protein Content (Protein) (%),319,15.94,2.33,5.56,14.46,15.87,17.43,24.81
Visceral Fat Rating (VFR),319,9.1,4.3,1.0,6.0,9.0,12.0,31.0
Bone Mass (BM),319,2.8,0.5,1.4,2.4,2.8,3.2,4.0
Muscle Mass (MM),319,54.3,10.6,4.7,45.8,53.9,62.6,78.8
Obesity (%),319,35.85,109.8,0.4,13.9,25.6,41.75,1954.0
Total Fat Content (TFC),319,23.5,9.6,3.1,17.0,22.6,28.6,62.5
Visceral Fat Area (VFA),319,12.17,5.26,0.9,8.57,11.59,15.1,41.0
Visceral Muscle Area (VMA) (Kg),319,30.4,4.5,18.9,27.2,30.4,33.8,41.1
Glucose,319,108.7,44.8,69.0,92.0,98.0,109.0,575.0
Total Cholesterol (TC),319,203.5,45.8,60.0,172.0,198.0,233.0,360.0
Low Density Lipoprotein (LDL),319,126.7,38.5,11.0,100.5,122.0,151.0,293.0
High Density Lipoprotein (HDL),319,49.5,17.7,25.0,40.0,46.5,56.0,273.0
Triglyceride,319,144.5,97.9,1.4,83.0,119.0,172.0,838.0
Aspartat Aminotransferaz (AST),319,21.7,16.7,8.0,15.0,18.0,23.0,195.0
Alanin Aminotransferaz (ALT),319,26.9,27.9,3.0,14.2,19.0,30.0,372.0
Alkaline Phosphatase (ALP),319,73.1,24.2,7.0,58.0,71.0,86.0,197.0
Creatinine,319,0.8,0.18,0.46,0.65,0.79,0.92,1.46
Glomerular Filtration Rate (GFR),319,100.82,16.97,10.6,94.17,104.0,110.74,132.0
C-Reactive Protein (CRP),319,1.85,4.99,0.0,0.0,0.22,1.62,43.4
Hemoglobin (HGB),319,14.42,1.78,8.5,13.3,14.4,15.7,18.8
Vitamin D,319,21.4,9.98,3.5,13.25,22.0,28.06,53.1